<?php

namespace App\Models;

use App\FirebasePush;
use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    protected $hidden = ['user_id'];
    protected $fillable = ['user_id', 'notificatable_type', 'notificatable_id', 'unique_id', 'title', 'body', 'thumb'];

/*    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function(Notification $notification) {
        });
    }*/

    #region Relations
    #endregion

    #region Mutators
    #endregion

    #region Accessors
    #endregion
}
