<?php

namespace App\Models;

use App\Http\Controllers\FileUploader;
use App\Traits\FavourableTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;

class Record extends Model
{
    use FavourableTrait;
    protected $appends = ['type_name', 'in_favourite'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleted(function(Record $record) {
            FileUploader::deleteFile($record->url ?? null);
        });
    }
    #region Relations
    #endregion

    #region Mutators
    #endregion

    #region Accessors
    public function getTypeNameAttribute() {
        $model_name = array_search(self::class, Relation::$morphMap);
        if (isset($this->attributes['type'])) {
            return trans('attributes.'.$this->type);
        }
        else if (isset($model_name)) {
            return trans('attributes.'.$model_name);
        }
        return '';
    }
    #endregion
}
